### ISSUE TITLE
Missing loader-utils

### ISSUE THREAD

**Issue by okhomenko** [bholloway/resolve-url-loader#1]
Getting error: "Error: Cannot find module 'loader-utils'"

**Comment by bholloway** [comment]
Understood. Should be an easy fix. Will get straight on it.

**Comment by bholloway** [comment]
Published new version `1.0.3` to NPM which should fix the problem. Please let me know how it goes.

The changes can be seen in this [commit](https://github.com/bholloway/resolve-url-loader/commit/a23a66ff6c5e0ec9055544d1d8d5a23488d42721).

My apologies for this omission. I'm glad you raised an issue.

**Comment by okhomenko** [comment]
Yep, now is good, but got another issue #2
