### ISSUE TITLE
Regular CSS imports handling (`@import url(../test.css);`)

### ISSUE THREAD

**Issue by andreyvolokitin** [bholloway/resolve-url-loader#104]
Does `resolve-url-loader` supposed to resolve regular CSS-imports? I have a setup where it successfully resolves background-image `url()`, but not touching @import `url()`, which fails later on the loader chain as unresolved

**Comment by bholloway** [comment]
@andreyvolokitin I think you are correct in your reasoning. Webpack expects the assets to be relative to the file it is considering. With SCSS it only sees only sees the base file and not the imports _within_ sass.

But in the case of the `.css` files,  I would expect the `css-loader` to correctly handle the `url()`. If the paths in the `.css` are not relative then you can probably fix this with `postcss` or some other css processor. But this is a separate issue to your `.scss` files and will probably need a separate `rule` with different loaders.

**Comment by andreyvolokitin** [comment]
Yeah, I figured out I can use `css-loader` with  `resolve.alias` in CSS-imports, thanks
