### ISSUE TITLE
defaultBasePath corrupted on windows

### ISSUE THREAD

**Issue by bholloway** [bholloway/resolve-url-loader#11]
Refer to late addition to #7.

Original comment by @meta-meta.

@bholloway I'm seeing this problem. following your advice

> If you want to hack some code then try logging value at sources-relative-to-absolute.js#L67 and let me know what you get.

what would it mean if on line 75, adding 

``` console.log(reduced);
console.log(value);
```

produces 

```
/
d:\
```

the root directory of my webpack project is d:\Projects/project
I am running Windows and my colleagues running on Mac do not experience this issue.

I am running into this error only on webpack-dev-server. webpack works fine

update: I'm seeing defaultBasePath passed to sourcesRelativeToAbsolute(sources, defaultBasePath, limit) is `/` and I'm not sure why that is as the output.path in my webpack.config is pointing to d:\Projects\project\build

my dirty hack for now is to add this as first line of sourcesRelativeToAbolute: `defaultBasePath = 'd:\\';`

**Comment by meta-meta** [comment]
Thanks @bholloway

**Comment by bholloway** [comment]
@meta-meta I do not have experience with `webpack-dev-server`. How practical would it be for you to construct a small open-source repo that exhibits the problem?

**Comment by meta-meta** [comment]
@bholloway I should be able to get to it sometime this weekend.

**Comment by joshuacc** [comment]
FWIW, I am seeing a similar warning on Windows when using webpack-dev-server, but no issues when running the normal webpack build.

**Comment by bholloway** [comment]
I don't like having this issue still open.

This not being my use-case it is a barrier to reproducing the issue. Until I can look at **webpack-dev-server**, or someone can give me a sample project that does, I am unable to move forward. Sorry I know that this is not a great answer.

**Comment by bholloway** [comment]
@cevou I noticed in your recent [comment](/bholloway/resolve-url-loader/issues/25#issuecomment-230674202) that you are using `webpack-dev-server`.

Can you add any insight to this issue? Seems to be only on windows so you may not have encountered it.

**Comment by cevou** [comment]
From the messages above I don't really get the use case. Is there some repo with which the error can be reproduced? I'm also using Windows, so I can check on it. 
@meta-meta does this problem still exist?

**Comment by bholloway** [comment]
I'm going to close this issue from inactivity. If this is still a problem lets open a fresh issue.
