### ISSUE TITLE
3.0.0 Breaks Relative Paths in CSS

### ISSUE THREAD

**Issue by epihel** [bholloway/resolve-url-loader#112]
In version `2.3.1`, fonts and images with relative paths referenced in CSS files work fine. But in `3.0.0`, if the path doesn't begin with `/`, `resolve-url-loader` inserts an `./includes/` directory before the path and produces the following error:

```
ERROR in ./src/css/main.css (./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js?sourceMap!./src/css/main.css)
Module not found: Error: Can't resolve './includes/public/fonts/myfont.otf' in '/Users/dev/src/css'
 @ ./src/css/main.css (./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js?sourceMap!./src/css/main.css) 9:41-106
 @ ./src/css/main.css
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3100 (webpack)/hot/dev-server.js ./src/index
```

The webpack config:
```
{
    test: /\.(css|scss)$/,
    loaders: ['style-loader', 'css-loader', 'resolve-url-loader', 'sass-loader?sourceMap']
}
```

The font declaration:
```
@font-face {
    font-family: "My Font";
    src: url("public/fonts/myfont.ttf") format('truetype'),
        url("public/fonts/myfont.otf") format('opentype');
}
```

The relevant dependencies/versions from package.json:
```
"css-loader": "2.1.0",
"react-hot-loader": "4.6.3",
"resolve-url-loader": "3.0.0",
"sass-loader": "7.1.0",
"style-loader": "0.23.1",
"webpack": "4.29.0",
"webpack-dev-server": "3.1.14"
```

**Comment by bholloway** [comment]
That’s strange. I’m guessing there is no “includes” directory in you project file system.

 This is not some special string in “resolve-URL-loader”.

Try the debug option in the loader to see what paths it is processing.

**Comment by bholloway** [comment]
Version 2 did a full file system search which has been discontinued.

It’s most likely your build relied on that.

It seems that the sass sourcemap attributes the URL statement to the includes folder. Do you have mixins  there that write the URL?

**Comment by bholloway** [comment]
Sorry I misread. You have already confirmed that this is the case.

The entire aim of this loader is to achieve the path relative to the original SCSS source file.

If you want relative to the complied CSS then simply remove this loader. Because the css loader already does what you want without further URL rewriting.

**Comment by epihel** [comment]
No; I don't have mixins that write the URL. Without `resolve-url-loader`, none of the relative font or image paths in the SCSS files are resolved. But I haven't been able to figure out any way to get this to work in `3.0.0.` I don't think I'm doing anything unusual. My loaders are:
```
{ test: /\.(css|scss)$/, use: [
    { loader: 'style-loader' },
    { loader: 'css-loader' },
    { loader: 'resolve-url-loader', options: { debug: true } },
    { loader: 'sass-loader', options: { sourceMap: true, sourceMapContents: false } }
] }
```

**Comment by bholloway** [comment]
Can you give some file paths relative to your project root.

Specifically
- the scss file getting imported
- a scss file in the includes directory that has URL statement
- the asset file referred to in that same URL statement

**Comment by bholloway** [comment]
@epihel it seems likely you have your assets in `public/`. In this case you have a couple of options. 
* Keep webpack ignorant of the assets - Use `css-loader?url=false` as documented in [css-loader options](https://github.com/webpack-contrib/css-loader#options). This means that the content of the `url()` statements will **not** become [a webpack module].(https://webpack.js.org/concepts/modules/#what-is-a-webpack-module).
* Let webpack manage the assets - Use the `css-loader` defaults. This means that webpack will want to locate any asset in the `url()` statements. So the path in the `url()` needs to be correct.

If you go with the latter option you might need to map all the `url()` statements to your project root directory. Probably you would use the [webpack resolve](https://webpack.js.org/configuration/resolve/) config to do this.

If you have to rebase the `url()` paths somewhere along the way keep in mind `postcss-loader` with the `postcss-url` plugin. This used to be possible with `postcss-loader` using the `root` option but they remove it [in this release](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes-1).

Keep in mind that `resolve-url-loader` is for the case where you co-locate your assets with your `scss` files in a feature-based structure. You will need to remove it to make any of this work.

**Comment by epihel** [comment]
Thanks for the tips. I was able to get it to work by removing `resolve-url-loader`, adding a tilde before all my font and image references (e.g., `~public/fonts/VC1/VC1-Regular.otf`), and adding the following to my webpack config:
```
resolve: {
    alias: {
        public: path.join(__dirname, 'src', 'public')
    }
}
```
