### ISSUE TITLE
NPM distributable contains huge /tmp/1536277707 directory

### ISSUE THREAD

**Issue by bguijt** [bholloway/resolve-url-loader#115]
Hi,

While checking for files to cleanup in my rather slow, huge /node_modules directory (997 packages, 65.269 files, 646MB), I stumbled upon resolve-url-loader (version 2.3.1) which has a rather large /tmp folder (14.521 files, 55.8MB) with files I don't seem to need. It makes for a quarter of all the files in my /node_modules.

Could you clarify what these are for? Can I just remove them?

**Comment by bholloway** [comment]
Wow my apologies if those are in the bundle.

🤔Just trying to release an update to `3.x.x` series. I'll try to look at a hotfix to `2.3.x` after that.

However I do encourage you to look at `3.x.x` because it should drop in to most project if you use `rework` engine.

**Comment by bguijt** [comment]
Thanks man! Hopefully 3.0.0 works with the Nativescript version I am using. Will try.

**Comment by bholloway** [comment]
@bguijt Just looking at `2.3.1`. The only change was to the readme. So certainly try `3.0.0` but worst case pin to `2.3.0`.

That said I will try to find some time to bump `2.3.0` to `2.3.2` without the superfluous files.

**Comment by bholloway** [comment]
* Deprecated `resolve-url-loader@2.3.1` (20.7 MB) using `npm`.
* Published `resolve-url-loader@2.3.2` without superfluous files  (27.5 kB).

| npm info resolve-url-loader@2.3.1 | npm info resolve-url-loader@2.3.2 |
|-----|-------|
| ![image](https://user-images.githubusercontent.com/6868309/52896985-e55f0f80-3222-11e9-9fca-eeee9d436462.png) | ![image](https://user-images.githubusercontent.com/6868309/52896989-ff98ed80-3222-11e9-87c3-a8b56fbbb9b0.png) |
