### ISSUE TITLE
resolve-url-loader not working properly with webpack 4 and dart-sass

### ISSUE THREAD

**Issue by thasmo** [bholloway/resolve-url-loader#122]
First time using `resolve-url-loader` and I think something's not working correctly when using `resolve-url-loader` with webpack 4 and `dart-sass`.

When enabling the `debug` option, `resolve-url-loader` prints this:
```
resolve-url-loader: ./assets/base/main.scss: ../../fonts/avenir-400.woff
  ./assets/base
  NOT FOUND
```

I'm not sure why the font file can't be found, but relative from the `main.scss` file, the location of the font file is `../../fonts/avenir-400.woff`.

My stylesheet-related webpack config part looks basically like this:
```
{ loader: 'css-loader', options: { sourceMap: false } },
{ loader: 'postcss-loader', options: { sourceMap: false } },
{
	loader: 'resolve-url-loader',
	options: {
		engine: 'postcss',
		sourceMap: false,
		debug: true,
	},
},
{
	loader: 'sass-loader',
	options: {
		sourceMap: true,
	},
},
```

**Comment by tracker1** [comment]
I'm having similar issues... 

```
    ERROR in ./assets/baseline.scss (../node_modules/css-loader??ref--7-1!../node_modules/postcss-loader/src??ref--7-2!../node_modules/resolve-url-loader??ref--7-3!../node_modules/sass-loader/lib/loader.js??ref--7-4!./assets/baseline.scss)
    Module not found: Error: Can't resolve '../../fonts/roboto-slab/Roboto-Slab-Bold.woff' in 'C:\Users\mryan\src\runbeck.visualstudio.com\vocem\rb-vocem\ui\_app\assets'
     @ ./assets/baseline.scss (../node_modules/css-loader??ref--7-1!../node_modules/postcss-loader/src??ref--7-2!../node_modules/resolve-url-loader??ref--7-3!../node_modules/sass-loader/lib/loader.js??ref--7-4!./assets/baseline.scss) 7:4049-4105 7:4323-4379
```

I'm referencing `roboto-fontface`

```
@import "~roboto-fontface/css/roboto/sass/roboto-fontface-regular.scss";
```

**Comment by bholloway** [comment]
I am not familiar with `dart-sass`. Can you provide a minimum breaking repo?

**Comment by thasmo** [comment]
@bholloway Not sure when I will have time to provide a repo but basically `dart-sass` can be used with the `sass-loader` by setting the `implementation` option.

```
    {
        loader: "sass-loader",
        options: {
            implementation: require("sass")
        }
    }
```

**Comment by thasmo** [comment]
@bholloway Found some time to create a [repo for sharing a simple reproduction case](https://github.com/thasmo/resolve-url-loader-dart-sass) and it seems `resolve-url-loader` does not handle `dart-sass` properly somehow. Using `node-sass` works anyway.

Afaik `sart-sass`, available as the `sass` package on `npm` is the new, de-facto reference implementation of Sass; the successor or `node-sass` so to speak.

I was wondering how `resolve-url-loader` would fail when using `dart-sass` anyway. Could it be that the source-map generation from `dart-sass` is not working properly?

**Comment by bholloway** [comment]
Thanks @thasmo I will try to take a look soon

**Comment by bholloway** [comment]
I added `adjust-sourcemap-loader` and `file-loader`.

In `debug` mode the `adjust-sourcemap-loader` will dump the sourcemap `sources` to stdout.
```
rules: [
  {
    test: /\.png$/,
    loader: 'file-loader',
  },
  {
    test: /\.(scss|css)$/,
    use: [
      {
        loader: 'style-loader',
      },
      {
        loader: 'css-loader',
      },
      {
        loader:  'resolve-url-loader',
      },
      {
        loader:  'adjust-sourcemap-loader',
        options: {
          debug: true,
        },
      },
      {
        loader: 'sass-loader',
        options: {
          implementation: sass, // comment this line out and it will work
          sourceMap: true,
        },
      },
    ],
  },
],
```

When `implementation` is commented there are definitely both the sources present.

```
adjust-sourcemap-loader:
  /mnt/c/.../resolve-url-loader-dart-sass/src/main.scss
        @ /mnt/c/.../resolve-url-loader-dart-sass/node_modules/sass-loader/lib/loader.js??ref--5-4
    INPUT src/main.scss
          src/dir/import.scss
 ABSOLUTE /mnt/c/.../resolve-url-loader-dart-sass/src/main.scss
          /mnt/c/.../resolve-url-loader-dart-sass/src/dir/import.scss
```

When `implementation` is as coded only the entry source is present.
```
adjust-sourcemap-loader:
  /mnt/c/.../resolve-url-loader-dart-sass/src/main.scss
        @ /mnt/c/.../resolve-url-loader-dart-sass/node_modules/sass-loader/lib/loader.js??ref--5-4
    INPUT src/main.scss
 ABSOLUTE /mnt/c/.../resolve-url-loader-dart-sass/src/main.scss
```

I have not looked deeper to see if there are some necessary options that are not being passed through to the implementation.

**Comment by pscheit** [comment]
ahum. So this is a problem from dart-sass? Shouldn't we file a issue then?
Is the workaround to not use dart-sass? :o

**Comment by bholloway** [comment]
This seems to have since been fixed _somewhere_ upstream.

If I rerun @thasmo [repo for sharing a simple reproduction case](https://github.com/thasmo/resolve-url-loader-dart-sass) then it now works.

Here is my debug output now
```
adjust-sourcemap-loader:
  /.../resolve-url-loader-dart-sass/src/main.scss
        @ /.../resolve-url-loader-dart-sass/node_modules/sass-loader/dist/cjs.js??ref--5-4
    INPUT src/dir/import.scss
          src/main.scss
 ABSOLUTE /.../resolve-url-loader-dart-sass/src/dir/import.scss
          /.../resolve-url-loader-dart-sass/src/main.scss
```

Given the order of sourcemap sources I suspect it was fixed by [this sass-loader PR](https://github.com/webpack-contrib/sass-loader/pull/681) from May 8.

@thasmo can you please confirm so that we can close out this issue and sass/dart-sass#819.

**Comment by thasmo** [comment]
Tested with my reproduction case (although the case seems to actually have never worked due to a missing loader configuration for the image 🤔) and another test-project and so far this really seems to work now. Thanks for your time and effort looking into it and informing about the fix. 👍 Awesome!

**Comment by larssn** [comment]
A heads up: This seems to be a problem with again with sass-loader 8.0.0, which was recently released. We had weird issues with relative paths suddenly, until we rolled back to 7.x.

**Comment by Nettsentrisk** [comment]
I'm getting this problem now with sass-loader 8.x, and adding adjust-sourcemap-loader doesn't help this time. Should the issue be handled here or with sass-loader?
