### ISSUE TITLE
How should the loader handle url pointing to anchor tags?

### ISSUE THREAD

**Issue by lainas262** [bholloway/resolve-url-loader#123]
This is more of a question.

Say you have an inline svg on your site and you have all styling related with that svg in your scss files, and as part of that styling there is a clip-path rule that points to an anchor like this:
`.st0 {
        clip-path : url(#XMLID_2_);
    }`
currently this throws an error that source-map information is not available at url() declaration. Is this a case that the loader knows how to handle?
note - external file urls work just fine like: 
`background-image: url("../../img/logo.png");`

**Comment by bholloway** [comment]
Usually `source-map information is not available` means that the incoming source-map is somehow corrupt. If you happen to be on windows then you should to look at the [windows line breaks](https://github.com/bholloway/resolve-url-loader/blob/master/packages/resolve-url-loader/README.md#windows-line-breaks) problem.

However you've said that external `url()` works. Does that mean it also works for the `clip-path` or just that other `url()` such as `background-image` work in the same file?

**Comment by bholloway** [comment]
Anything further on this @lainas262 ?

**Comment by bholloway** [comment]
Closing for now due to lack of activity.
