### ISSUE TITLE
resolve-url-loader can not coexist with cssnano

### ISSUE THREAD

**Issue by didiself** [bholloway/resolve-url-loader#130]
My site base on Nextjs. When cssnano coexist with resolve-url-loader , resolve-url-loader not work.

scss:
```
background: url("./loading.png");
```
webpack:
```
rule.use.splice(cssLoaderIndex + 1, 0, {
              loader: 'postcss-loader',
              options: {
                plugins: [
                  require('postcss-flexbugs-fixes'),
                  require('autoprefixer'),
                  require('cssnano')({
                    preset: 'default',
                    normalizeUrl:false
                  })
                ]
              }
            })

            const isCss = /\\\.css\$/.test(rule.test + '')
            !isCss &&rule.use.splice(cssLoaderIndex + 1, 0, {
              loader: 'resolve-url-loader',
              options: {
                // engine: 'rework',
                keepQuery:true,
                debug:true,
                sourceMap: true
              }
            })
```

When cssnano +resolve-url-loader :
![image](https://user-images.githubusercontent.com/14201030/63339757-2e318580-c378-11e9-9846-3a2d2728668b.png)

When cssnano remove: resolve-url-loader work!!

So, how can I fix it?

**Comment by terox** [comment]
I think that it could be related also with #129

**Comment by bholloway** [comment]
@terox please ensure that `resolve-url-loader` occurs immediately _after_ `sass-loader`. I suspect that you have `css-nano` in between, which would probably break things.

Otherwise please create an open-source repo with a minimum breaking example that I can look at.

**Comment by bholloway** [comment]
Closing from lack of response. Happy to reopen if any of the existing participants are still having problems.
