### ISSUE TITLE
This module breaks SASS modules composition in CRA

### ISSUE THREAD

**Issue by Igor10k** [bholloway/resolve-url-loader#131]
Updated my CRA to the latest version and the build started failing. A little debugging showed that removing the `resolve-url-loader` fixes the issue.

The error is thrown when trying to use the CSS modules composition feature with a css preprocessor. Composing from a SASS module doesn't work. Composing from a CSS module works.

### Thrown error
```
./src/b.module.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-6-3!./src/b.module.sass)
Error: resolve-url-loader: CSS error
  ./src/b.module.sass:2:3: Unknown word
You tried to parse Sass with the standard CSS parser; try again with the postcss-sass parser
  You tried to parse Sass with the standard CSS parser; try again with the postcss-sass parser
```

### Steps to reproduce

1. `npx create-react-app test_app && cd test_app`
2. `yarn add node-sass`
3. Create `b.module.sass` with
```
.test
  background: #FFF
```
4. Create `a.module.sass` with
```
.test
  composes: test from './b.module.sass`
```
5. In `App.js` add as the first line `import './a.module.sass'`
6. `yarn start` and observe the error

---

7. Rename `b.module.sass` to `b.module.css` and replace the contents with
```
.test {
  background: #FFF;
}
```
8. In `a.module.sass` change `b.module.sass` to `b.module.css`
9. Observe that the error is gone

**Comment by Igor10k** [comment]
Debugged a bit more and found what exactly is breaking the build. So edited the issue to reflect that.

**Comment by bholloway** [comment]
It seems this is a [css-loader issue](https://github.com/webpack-contrib/css-loader/issues/131).

The same issue has been opened on a number of loaders. It would be consistent with those cases to close this issue here. However I suspect that would just lead to people creating more issues so I will leave open for now.

**Comment by shahan953** [comment]
Error: resolve-url-loader: CSS error
  source-map information is not available at url() declaration (found orphan CR, try removeCR option)


error Command failed with exit code 1.


I'm getting this error when I try to build my project using react-scripts

**Comment by bholloway** [comment]
@shahan953 that error is not relevant to this issue. Please [follow the docs](https://github.com/bholloway/resolve-url-loader/blob/v4-development/packages/resolve-url-loader/README.md#windows-line-breaks).

**Comment by bholloway** [comment]
@Igor10k is this still an issue in CRA? Everything I read points to this being fixed.

**Comment by bholloway** [comment]
In the mean time I'm going to close this issue. Please let me know if it is still a problem and we can reopen.
