### ISSUE TITLE
Module build failed: Error: missing '{'

### ISSUE THREAD

**Issue by Gummibeer** [bholloway/resolve-url-loader#132]
I get this error if I run `yarn prod`

> ERROR in ./resources/assets/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: file:///resources/assets/sass/app.scss:3:412: missing '{'

If I switch back to v2 it's only a warning and the files are processed:

> WARNING in ./resources/assets/sass/app.scss (./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--8-4!./node_modules/sass-loader/dist/cjs.js??ref--8-5!./resources/assets/sass/app.scss)
Module Warning (from ./node_modules/resolve-url-loader/index.js):
(Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
  /Users/tomwitkowski/Projects/private/page-template/resources/assets/sass/app.scss:3:404: missing '{'

**webpack.mix.js**
```js
const mix = require('laravel-mix');
const tailwindcss = require('tailwindcss');
require('laravel-mix-purgecss');

mix
    .setPublicPath('public')
    .babel('resources/assets/js/app.js', 'public/js/app.js')
    .sass('resources/assets/sass/app.scss', 'css')
    .sass('resources/assets/sass/fonts.scss', 'css')
    .version()
    .options({
        processCssUrls: true,
        postCss: [ tailwindcss('./tailwind.config.js') ],
    })
    .purgeCss()
;
```

**app.scss**
```scss
@tailwind base;

@tailwind components;

@tailwind utilities;
```

In `fonts.scss` I use font awesome from node_modules. So I would like to let webpack copy the fonts. The error doesn't occur if I set `processCssUrls: false`.

These are my dev dependencies:

```json
"devDependencies": {
  "cross-env": "^6.0.0",
  "laravel-mix": "^4.1.0",
  "laravel-mix-purgecss": "^4.1.0",
  "prettier": "^1.18.2",
  "resolve-url-loader": "^3.1.0",
  "sass": "^1.22.12",
  "sass-loader": "^7.3.1",
  "webpack": "^4.0.0"
},
```

I've opened a related issue https://github.com/tailwindcss/tailwindcss/issues/1132

**Comment by bholloway** [comment]
From what I can gather those tailwind directives are not valid CSS. The tailwind plugin will process and substitute them for valid declarations.

In fact, tailwind [warns that it only reliably works with postcss](https://tailwindcss.com/docs/using-with-preprocessors/#using-postcss-as-your-preprocessor).

Since `resolve-url-loader@3.x.x` we use `engine: 'postcss'` by default. So ideally I'd like you to prove that the tailwind syntax is compatible with vanilla postcss. If you can do that then I will make the necessary changes to `resolve-url-loader` to make this work.

Alternatively you could keep using `resolve-url-loader@3.x.x` downgrade to the old engine using `engine: 'rework'`.

**Comment by bholloway** [comment]
@Gummibeer looking again at this issue. I suspect you have some other css problem.

`Error: file:///resources/assets/sass/app.scss:3:412: missing '{'` seems to me the error is not in the parsing of the tailwind declarations.

Can you please supply a minimum breaking example as open-source repo.

**Comment by vrushank** [comment]
I'm also facing similar issue. While checking all of my scss files, I found that removing `@apply` code from scss resolve this issue. I suggest @Gummibeer to check your scss files once and if you find `@apply` in your scss file, remove that code and build your project again. I'm also not sure if this is an issue with tailwind or resolve-url-loader but the error is generated from resolve-url-loader.

**Comment by Gummibeer** [comment]
There is no `@apply` only the three tailwind directives are in the `app.scss`. 
I will create a public repo with minimum setup today.

**Comment by Gummibeer** [comment]
Here it is - have reduced it to the absolute minimum. Could even reduce it to a single `@tailwind ...` line.
https://github.com/Gummibeer/tailwind-process-css-urls

I've created a second branch `warning-only` - it only changes the `resolve-url-loader` version to `^2.3.0`. In this branch the file gets processed, a warning occurs in terminal but the `app.css` file is created, with content, and no CSS error - following my IDE.

**Comment by bholloway** [comment]
@Gummibeer thanks for that example the problem in this case is now obvious to me.

I can see that `laravel-mix@master` is explicitly using the `engine: rework` for some perceived backwards compatibility, even though the `engine: postcss` should be the safer option.

Refer to [here](https://github.com/JeffreyWay/laravel-mix/blob/98434a367dee6df7212d864455b2922c91435faf/src/components/Preprocessor.js#L79). If you monkey-patch your local `node_modules` to remove that option you will find it works.

I suggest that you open an issue on `laravel-mix` to have the option removed and add the ability to specify `resolve-url-loader` options even if it is an undocumented escape hatch. I make the default options as safe as possible but there are situations (like the `removeCR` fix) where configuration is needed per-project.

If you do that you can link this comment and/or mention me there.

**Comment by bholloway** [comment]
I see that `engine` option is no longer specified in `laravel-mix` 👍 

I'm going to close this issue.
