### ISSUE TITLE
[Request] Add extract-text-webpack-plugin Support 

### ISSUE THREAD

**Issue by full-of-foo** [bholloway/resolve-url-loader#14]
This plugin does not currently respect the Webpack [`ExtractTextPlugin`](https://github.com/webpack/extract-text-webpack-plugin)

```javascript
module: {
    loaders: [
        { test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader!css-loader!resolve-url") },
        { test: /\.(png|jpg)$/, loader: 'url-loader?name=[path][name].[ext]?[hash]'},
        { test: /\.(woff|svg|ttf|eot)([\?]?.*)$/, loader: "file-loader?name=[name].[ext]?[hash]"}
    ]
}
plugins: [
    new ExtractTextPlugin('css/[name].bundle.css', {allChunks: true})
]
```
```
~/foo/node_modules/extract-text-webpack-plugin/index.js:118
	Object.keys(b).forEach(function(key) {
	       ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at mergeOptions (/~/foo/node_modules/extract-text-webpack-plugin/index.js:118:9)
    at Function.ExtractTextPlugin.extract (~/foo/node_modules/extract-text-webpack-plugin/index.js:134:29)
    at Object.<anonymous> (~/foo/webpack.config.js:34:57)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by bholloway** [comment]
I can show [an example of `extract-text-webpack-plugin` working](https://github.com/angularity/webpack-angularity-solution/blob/master/index.js#L88). But that said I am definitely interested in how your use case is not working.

I can immediately see that you have only one loader specified in `extract()`.

```javascript
ExtractTextPlugin.extract([notExtractLoader], loader, [options])
```

Has this first option (`notExtractLoader`) always been optional? Anyhow just now I omitted it and everything still worked.

Do you have any other warnings in your failing build? It may be that `resolve-url-loader` is warning that it cannot operate.

**Comment by bholloway** [comment]
On second look I think that you should be using the `style-loader` as your `nonExtractLoader` only. If you never intend to disable the plugin then just remove it completely.

Event if this does not solve the error at hand I think it will be a problem for you following.

**Comment by bholloway** [comment]
Hey @full-of-foo. How did you go with this?

**Comment by full-of-foo** [comment]
@bholloway I opted to use npm packages over bower packages for my frontend deps which ultimately fixed my URL loading issues, so in the end I did not need `resolve-url-loader`. Sorry this isn't much help

**Comment by bholloway** [comment]
Ok @full-of-foo I'm going to close this for now. If anyone else encounters this I can reopen.

In some of my applications I am also using **Bower** and experience a lot of issues as a result. Definitely **npm** is the happy path so go with that where you can.
