### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by bard83** [bholloway/resolve-url-loader#145]
The license mentioned on npm is MIT. There is no license file inside, it would be great to have it.

Thanks in advanced.

**Comment by bholloway** [comment]
Check the npm distribution you should find it there.

There is no licence in the monorepo root but you do not consume the repo.

Let me know if it isn’t in the npm distribution.

**Comment by bard83** [comment]
My bad, we have an automatic tool that grab all the licenses. We have realized that we have a bug on grabbing files named  using UK notation (LICENCE).
Thanks and sorry.
