### ISSUE TITLE
Wrapping double quotes escaped in output

### ISSUE THREAD

**Issue by fanchyfanch** [bholloway/resolve-url-loader#152]
My URL declarations are wrapped with double-quotes in my sources files but when I compile them using Webpack Encore, double-quotes have disappeared from output files.

> url("../../../../fonts/caviar-dreams/CaviarDreams-regular.ttf")

becomes 

> url(/build/fonts/CaviarDreams-regular.ttf)

----

"@symfony/webpack-encore": "0.28.2"
"node-sass": "^4.13.0"
"sass-loader": "^7.0.1"

**Comment by bholloway** [comment]
@fanchyfanch sorry for the delay in replying. 

IIRC this occurs in the `css-loader`. You can see in their test fixured [here](https://github.com/webpack-contrib/css-loader/blob/d2f6bd2755a513e98faca84c3f52544be72d53f3/test/fixtures/basic.css#L9) there are double quotes which are not present in the snapshot [here](https://github.com/webpack-contrib/css-loader/blob/d2f6bd2755a513e98faca84c3f52544be72d53f3/test/__snapshots__/loader.test.js.snap#L207).

I will close this for now and reopen if necessary.
