### ISSUE TITLE
Error: This relative module was not found

### ISSUE THREAD

**Issue by luckylooke** [bholloway/resolve-url-loader#153]
Hello 
thank you for sharing code with community. ❤️ 
I cannot find what the problem is here, Error:

>  ERROR  Failed to compile with 1 errors                                                                                          9:10:27 AM
> 
> This relative module was not found:
> \* ../assets/images/logo.png in ./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/resolve-url-loader??ref--8-oneOf-1-3!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-4!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=style&index=0&id=469af010&scoped=true&lang=scss&

Chain:
./src/components/HelloWorld.vue has <style> attribute which is prepended by @import "ui-lib_vars"
as configured in sass-loader options
```
prependData: `
          	@import "ui-lib_vars";
        `
```
in ui-lib_vars 
$ui-logo-bg: url('#{$ui-imagesPath}logo.png');
where
$ui-imagesPath: '../assets/images/';
which is corret relative path to the resource..

what is interesting that fonts are referenced the same and they dont argue about "module was not found" but it does not load correctly either.. it loads some unknown basic font and there are warnings in console

```
localhost/:1 Failed to decode downloaded font: data:font/woff2;base64,bW9kdWxlLmV4cG9ydHMgPSAiYXNzZXRzL2ZvbnRzL0JlYmFzTmV1ZS1XZWIud29mZjIiOw==
localhost/:1 Failed to decode downloaded font: data:font/woff;base64,bW9kdWxlLmV4cG9ydHMgPSAiYXNzZXRzL2ZvbnRzL0JlYmFzTmV1ZS1XZWIud29mZiI7
localhost/:1 Failed to decode downloaded font: data:font/ttf;base64,bW9kdWxlLmV4cG9ydHMgPSAiYXNzZXRzL2ZvbnRzL0JlYmFzTmV1ZS1XZWIudHRmIjs=
12OTS parsing error: invalid version tag
```

This is repo with reproduction:
https://github.com/luckylooke/laravel-vue-cli

I have also asked on SO, with some additional details. 
https://stackoverflow.com/questions/60917070/scss-how-to-load-style-url-references-relative-to-source-files-error-relative
You can answer there to get reputation points.

Thank you for any helpful info 🙏

**Comment by bholloway** [comment]
@luckylooke sorry for the delay. Did you find a fix?

It seems that the font is being referenced correctly but is being base64 encoded? I am unsure.

**Comment by luckylooke** [comment]
I ended up copying all style url referenced files from library to dependent project.. so now I have duplicated library assets, wich is not a good design. Is there a example project of your lib usage? :pray:

**Comment by bholloway** [comment]
There are basic examples in the `packages/resolve-url-loader/test` directory used for e2e tests but no full example.

> Is there a example project of your lib usage?

The problem is that there is a wide variety of webpack usages and this is just one loader that doesn't do very much. I guess you would have to look at [projectsdependent on this package](https://www.npmjs.com/browse/depended/resolve-url-loader) of which there are a few.

Please reopen if you would like more help with your specific problem.
