### ISSUE TITLE
Join Option Error

### ISSUE THREAD

**Issue by dwhiting10** [bholloway/resolve-url-loader#154]
I am trying to set up some custom processing of URLs using the join option.  I am probably missing something obvious, but just doing a simple test like:

`{
    loader: "resolve-url-loader",
    options:
    {
        sourceMap: true,
        join: function(uri, base)
        {
            return 'test-url';
        },
        debug: true,
    }
}`

Returns an error "Module build failed (from ./node_modules/resolve-url-loader/index.js): Error: resolve-url-loader: CSS error join is not a function"
Any help would be appreciated.

**Comment by quentin-dietz** [comment]
I ran into the same issue, and managed to fix it using the following config:
```  
{
    loader: 'resolve-url-loader',
    options: {
      root: '',
      join: (a,b) => {return (c,d) => {
        return `./${c}`
      }}
      }
  },
```

Essentially the join function should return a function, and that seems to work.

**Comment by bholloway** [comment]
Thanks @quentin-dietz 🙏 . Closing as solved.

I will improve the docs in the next release.
