### ISSUE TITLE
object-path high severity vulnerability

### ISSUE THREAD

**Issue by ChunxiAlexLuo** [bholloway/resolve-url-loader#170]
│ Path          │ resolve-url-loader > adjust-sourcemap-loader > object-path   │

https://www.npmjs.com/advisories/1573

**Comment by ChunxiAlexLuo** [comment]
https://github.com/bholloway/adjust-sourcemap-loader/pull/17

**Comment by suzuki-srj** [comment]
They will drop `object-path` package and release it.
https://github.com/bholloway/adjust-sourcemap-loader/pull/17

**Comment by malkrad** [comment]
published in 3.0.0 https://github.com/bholloway/adjust-sourcemap-loader/issues/16#issuecomment-712640330

**Comment by bholloway** [comment]
Published `resolve-url-loader@3.1.2`
