### ISSUE TITLE
Broken @page handling (again)

### ISSUE THREAD

**Issue by christianl-das** [bholloway/resolve-url-loader#178]
I'm experiencing the exact same issues as were described in #39 with the current version.

I upgraded from v2.3.1 to v3.1.2 as part of a security update for other dependencies and my build broke in exactly the same way as is described in that old issue.

After the upgrade, I noticed that v2.3.1 had already thrown a warning about the same issue but that warning has now been promoted to an error.

The top level package which pulls in `resolve-url-loader` for me is `laravel-mix@5.0.7` if that helps.

**Comment by bholloway** [comment]
@christianl-das can you please take a look at [this comment](https://github.com/bholloway/resolve-url-loader/issues/132#issuecomment-533834332) since I suspect the root cause may be the same.

**Comment by christianl-das** [comment]
Thanks for the quick response. I'm sorry that I didn't think of searching the issues for `laravel-mix`. The proposed fix seems to work fine for me.

**Comment by bholloway** [comment]
> Thanks for the quick response

Haha no problem, I was at the computer for once. Glad you got something working I know it can be difficult. 👍 

Have a couple of open issues due to frameworks. Once I release V4 I will push harder for them to address.

**Comment by christianl-das** [comment]
It looks like v6 of `laravel-mix` will address the problem. At least that line that explicitly uses `rework` isn't there any more in `master`.
