### ISSUE TITLE
hyperlink issue on docs troubleshooting page.

### ISSUE THREAD

**Issue by JasonHoku** [bholloway/resolve-url-loader#182]
https://github.com/bholloway/resolve-url-loader/blob/76b6296359c2ae45e3f86a4234ec1d6e09c739fd/packages/resolve-url-loader/docs/troubleshooting.md#options

This link redirect and sentence is not intuitively linear.

![image](https://user-images.githubusercontent.com/6715569/99524519-9df83c80-293c-11eb-8946-b6caa43246cb.png)

**Comment by bholloway** [comment]
Good catch :thumbsup:

I'm revising the docs so I'll go through and check all the links before doing anything further.

**Comment by bholloway** [comment]
Should be fixed now.

I also made it clear that the docs in the default branch are not the current release.
