### ISSUE TITLE
Proposal: Default removeCR=true on Window OS

### ISSUE THREAD

**Issue by bholloway** [bholloway/resolve-url-loader#195]
Per #194.

The issue with orphan CR from `libsass` is not something likely to be fixed soon.

The proposal is to default the `removeCR` option to `true` when on the Windows platform (or more specifically any platform where `os.EOL` includes `\r`).

If this change were part of the V4 beta then it might drive early adoption of V4.

Please vote with 👍  or 👎  emoji

**Comment by lucaslisboa** [comment]
I made a script and added it to package.json to run temporarily...

`powershell -Command "(gc ./node_modules/resolve-url-loader/index.js) -replace 'removeCR : false', 'removeCR : true' | Out-File -encoding ASCII ./node_modules/resolve-url-loader/index.js"`

**Comment by bholloway** [comment]
Having thought more, I'm going to implement the proposed default.
```
removeCR : os.EOL.includes('\r'),
```

Anyone have objections state them now.

**Comment by bholloway** [comment]
The interesting thing is that `libsass` claim this bug is fixed.

@shaurcasm @lucaslisboa can you please tell me which version of `libsass` are you using?

**Comment by bholloway** [comment]
Published `resolve-url-loader@4.0.0-beta.2` as tag `next`. 🎉 

Closing as implemented. Discussion can continue as needed.
