### ISSUE TITLE
@keyframes missing '}'

### ISSUE THREAD

**Issue by okhomenko** [bholloway/resolve-url-loader#2]
Module build failed: Error: undefined:14612:3: @keyframes missing '}'

As far as I understand it is problem with rework

**Comment by bholloway** [comment]
Is your project open source so I can debug? Its just that I'm not seeing the problem with any of mine.

Alternatively if you can locate the issue you could do a pull request.

**Comment by bholloway** [comment]
Is there a syntax error in your input `css` that rework is failing to parse? I will experiment with these sort of issues and try to reproduce.

Any further input will definitely help.

**Comment by bholloway** [comment]
@okhomenko I reproduced your error (or at least a result) by omitting a closing brace in a raw `css` file and adding that `css` file to my compilation.

I have published [`1.1.0`](https://www.npmjs.com/package/resolve-url-loader) on npm. The loader will now degrade gracefully on incoming `css` errors. However you may find that following loaders will not do so.

Please let me know if this solves your issue.

**Comment by bholloway** [comment]
@okhomenko I believe I have fixed this. Please let me know otherwise I will close this issue.

**Comment by okhomenko** [comment]
@bholloway Thank you so much. There is still problem with @keyframes, it's not related to resolve-url, but now at least I'm able to compile.
