### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by simon2k** [bholloway/resolve-url-loader#20]
Hi @bholloway, could you specify license in this project?

**Comment by bholloway** [comment]
Sorry for the delay, I have been travelling overseas.

I generally use MIT licence. I will add to the `package.json` and as a file in the root directory.

**Comment by bholloway** [comment]
Ok was already in the `package.json` but I've also added the github style `LICENCE` file in the root directory.

**Comment by simon2k** [comment]
Thanks!
