### ISSUE TITLE
postcss Denial of Service

### ISSUE THREAD

**Issue by TerrenceBerg** [bholloway/resolve-url-loader#203]
I have a problem with "postcss": "^7.0.35", 
When I run npm audit this is what I get. 
postcss  7.0.0 - 8.2.9
Severity: moderate
Regular Expression Denial of Service - https://npmjs.com/advisories/1693
fix available via `npm audit fix --force`
Will install resolve-url-loader@2.3.2, which is a breaking change
node_modules/resolve-url-loader/node_modules/postcss
  resolve-url-loader  3.0.0-alpha.1 - 4.0.0
  Depends on vulnerable versions of postcss
  node_modules/resolve-url-loader

**Comment by bholloway** [comment]
Please refer to #198 for solutions

**Comment by TerrenceBerg** [comment]
Thank you Ben!
