### ISSUE TITLE
moderate severity vulnerabilities from postcss < 8.2.10

### ISSUE THREAD

**Issue by wiesesascha** [bholloway/resolve-url-loader#205]
### Issue
postcss from 7.0.0 and before 8.2.10 are vulnerable to Regular Expression Denial of Service (ReDoS) during source map parsing:
https://www.npmjs.com/advisories/1693

### Reproduction
`npm i resolve-url-loader`

### Remediation
Upgrade to version 8.2.10 or later

**Comment by bholloway** [comment]
Please see #198
