### ISSUE TITLE
resolve-url-loader: error initialising   -   Cannot find module 'rework'

### ISSUE THREAD

**Issue by graterol-oswaldo** [bholloway/resolve-url-loader#211]
Hi, i have this error when i'm trying to run "npm run prod", can someone help me please?

> prod
> npm run production

> production
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
302 │ $headings-margin-bottom:      $spacer / 2 !default;
    │                               ^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 302:31  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 2:9                                           root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-padding-y, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
498 │ $input-height-inner-quarter:            add($input-line-height * .25em, $input-padding-y / 2) !default;
    │                                                                         ^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 498:73  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 2:9                                           root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($custom-control-indicator-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
568 │ $custom-switch-indicator-border-radius:         $custom-control-indicator-size / 2 !default;
    │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 568:49  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 2:9                                           root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
713 │ $nav-divider-margin-y:              $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 713:37  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 2:9                                           root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
718 │ $navbar-padding-y:                  $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 718:37  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 2:9                                           root stylesheet

WARNING: 86 repetitive deprecation warnings omitted.

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
302 │ $headings-margin-bottom:      $spacer / 2 !default;
    │                               ^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 302:31  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 2:9                                           root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-padding-y, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
498 │ $input-height-inner-quarter:            add($input-line-height * .25em, $input-padding-y / 2) !default;
    │                                                                         ^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 498:73  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 2:9                                           root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($custom-control-indicator-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
568 │ $custom-switch-indicator-border-radius:         $custom-control-indicator-size / 2 !default;
    │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 568:49  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 2:9                                           root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
713 │ $nav-divider-margin-y:              $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 713:37  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 2:9                                           root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
718 │ $navbar-padding-y:                  $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_variables.scss 718:37  @import
    node_modules/bootstrap/scss/bootstrap.scss 9:9      @import
    stdin 2:9                                           root stylesheet

WARNING: 86 repetitive deprecation warnings omitted.

 ERROR  Failed to compile with 2 errors                                                                                                1:53:50 AM

 error  in ./resources/sass/app.scss

Module Error (from ./node_modules/resolve-url-loader/index.js):
resolve-url-loader: error initialising
  Cannot find module 'rework'
Require stack:
- /source/app/node_modules/resolve-url-loader/lib/engine/rework.js
- /source/app/node_modules/resolve-url-loader/index.js
- /source/app/node_modules/loader-runner/lib/loadLoader.js
- /source/app/node_modules/loader-runner/lib/LoaderRunner.js
- /source/app/node_modules/webpack/lib/NormalModule.js
- /source/app/node_modules/webpack/lib/NormalModuleFactory.js
- /source/app/node_modules/webpack/lib/Compiler.js
- /source/app/node_modules/webpack/lib/webpack.js
- /source/app/node_modules/webpack-cli/bin/utils/validate-options.js
- /source/app/node_modules/webpack-cli/bin/utils/convert-argv.js
- /source/app/node_modules/webpack-cli/bin/cli.js
- /source/app/node_modules/webpack/bin/webpack.js
  Require stack:

 @ ./resources/sass/app.scss 2:14-253

 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/css-loader/index.js):
ModuleError: Module Error (from ./node_modules/resolve-url-loader/index.js):
resolve-url-loader: error initialising
  Cannot find module 'rework'
Require stack:
- /source/app/node_modules/resolve-url-loader/lib/engine/rework.js
- /source/app/node_modules/resolve-url-loader/index.js
- /source/app/node_modules/loader-runner/lib/loadLoader.js
- /source/app/node_modules/loader-runner/lib/LoaderRunner.js
- /source/app/node_modules/webpack/lib/NormalModule.js
- /source/app/node_modules/webpack/lib/NormalModuleFactory.js
- /source/app/node_modules/webpack/lib/Compiler.js
- /source/app/node_modules/webpack/lib/webpack.js
- /source/app/node_modules/webpack-cli/bin/utils/validate-options.js
- /source/app/node_modules/webpack-cli/bin/utils/convert-argv.js
- /source/app/node_modules/webpack-cli/bin/cli.js
- /source/app/node_modules/webpack/bin/webpack.js
  Require stack:
    at Object.emitError (/source/app/node_modules/webpack/lib/NormalModule.js:173:6)
    at handleAsError (/source/app/node_modules/resolve-url-loader/index.js:282:12)
    at Object.resolveUrlLoader (/source/app/node_modules/resolve-url-loader/index.js:204:12)

 26 assets

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/dist/cjs.js??ref--5-5!./resources/sass/app.scss)
Module Error (from ./node_modules/resolve-url-loader/index.js):
resolve-url-loader: error initialising
  Cannot find module 'rework'
Require stack:
- /source/app/node_modules/resolve-url-loader/lib/engine/rework.js
- /source/app/node_modules/resolve-url-loader/index.js
- /source/app/node_modules/loader-runner/lib/loadLoader.js
- /source/app/node_modules/loader-runner/lib/LoaderRunner.js
- /source/app/node_modules/webpack/lib/NormalModule.js
- /source/app/node_modules/webpack/lib/NormalModuleFactory.js
- /source/app/node_modules/webpack/lib/Compiler.js
- /source/app/node_modules/webpack/lib/webpack.js
- /source/app/node_modules/webpack-cli/bin/utils/validate-options.js
- /source/app/node_modules/webpack-cli/bin/utils/convert-argv.js
- /source/app/node_modules/webpack-cli/bin/cli.js
- /source/app/node_modules/webpack/bin/webpack.js
  Require stack:
 @ ./resources/sass/app.scss 2:14-253

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleError: Module Error (from ./node_modules/resolve-url-loader/index.js):
resolve-url-loader: error initialising
  Cannot find module 'rework'
Require stack:
- /source/app/node_modules/resolve-url-loader/lib/engine/rework.js
- /source/app/node_modules/resolve-url-loader/index.js
- /source/app/node_modules/loader-runner/lib/loadLoader.js
- /source/app/node_modules/loader-runner/lib/LoaderRunner.js
- /source/app/node_modules/webpack/lib/NormalModule.js
- /source/app/node_modules/webpack/lib/NormalModuleFactory.js
- /source/app/node_modules/webpack/lib/Compiler.js
- /source/app/node_modules/webpack/lib/webpack.js
- /source/app/node_modules/webpack-cli/bin/utils/validate-options.js
- /source/app/node_modules/webpack-cli/bin/utils/convert-argv.js
- /source/app/node_modules/webpack-cli/bin/cli.js
- /source/app/node_modules/webpack/bin/webpack.js
  Require stack:
    at Object.emitError (/source/app/node_modules/webpack/lib/NormalModule.js:173:6)
    at handleAsError (/source/app/node_modules/resolve-url-loader/index.js:282:12)
    at Object.resolveUrlLoader (/source/app/node_modules/resolve-url-loader/index.js:204:12)
 @ ./resources/sass/app.scss
node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/source/app/public/build/dist'
    at Object.statSync (node:fs:1526:3)
    at Object.statSync (/source/app/node_modules/graceful-fs/polyfills.js:312:16)
    at checkStats (/source/app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:171:22)
    at checkPaths (/source/app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:183:31)
    at Object.copySync (/source/app/node_modules/fs-extra/lib/copy-sync/copy-sync.js:25:20)
    at publishAseets (/source/app/webpack.mix.js:51:6)
    at /source/app/webpack.mix.js:40:28
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/source/app/public/build/dist'
}

**Comment by bholloway** [comment]
Please check the changelog.

you need to add rework as a dependency if you want to jeep using it.
