### ISSUE TITLE
css-loader v6.x - redundant functionality?

### ISSUE THREAD

**Issue by strarsis** [bholloway/resolve-url-loader#216]
[`css-loader` release  `6`](https://github.com/webpack-contrib/css-loader/releases/tag/v6.0.0) appears to have introduced native URL handling. Would this `resolve-url-loader` plugin still make sense when `css-loader` `6.x`+ is used?

**Comment by thasmo** [comment]
@bholloway, do you know that? Thanks!

**Comment by thasmo** [comment]
Nevermind, it [seems that it is needed](https://github.com/webpack-contrib/sass-loader#problems-with-url) after all.
