### ISSUE TITLE
v5 release

### ISSUE THREAD

**Issue by stof** [bholloway/resolve-url-loader#218]
The 5.0 version is in beta since June 2021. Is there any plan to make a stable release for it ?

**Comment by bholloway** [comment]
Yes this month. I am addressing some minor issues.

**Comment by bholloway** [comment]
I expect to release `resolve-url-loader@5.0.0` tomorrow.

**Comment by bholloway** [comment]
Released `resolve-url-loader@5.0.0` as dist-tag `latest`.
Removed dist-tag `next`.
