### ISSUE TITLE
Failing to add prefix to urls.

### ISSUE THREAD

**Issue by alexprice91** [bholloway/resolve-url-loader#35]
My local environment is setup to work like this:

`localhost:8080`

But my production environment looks like this:

`https://domain.com/prefix`.

I have gotten all my code to behave nicely with this, except for my images loaded from sass. So my css looks like this: 

`background-image: url(/images/logos/logo.svg);`

When it should output like this:

`background-image: url(/prefix/images/logos/logo.svg);`

Any help is appreciated!

**Comment by alexprice91** [comment]
For reference, I setup my publicPath within webpack, but that didn't work either.

**Comment by bholloway** [comment]
Can you please show your loader configuration for `scss`.

**Comment by alexprice91** [comment]
```
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract(['css', 'sass'], {
          publicPath: '/root'
        }),
      },
```

**Comment by ealves-pt** [comment]
I have a similar problem. @alexprice91 did you find any solution for this?

**Comment by bholloway** [comment]
Try adding the sourceMap option to sass loader.

**Comment by bholloway** [comment]
Try adding the [sourceMap option](https://github.com/bholloway/resolve-url-loader#source-maps-required) to sass loader.

**Comment by bholloway** [comment]
@alexprice91 How are you going with this? Did you fix your problem?

**Comment by bholloway** [comment]
I'm going to close due to lack of activity. We can always reopen.

@alexprice91 please ask further questions here until you are happy. @ealves-pt sounds like you are already there but same goes for you otherwise.

Anyone else please open a new issue.
