### ISSUE TITLE
query string and hash not working

### ISSUE THREAD

**Issue by craigcosmo** [bholloway/resolve-url-loader#40]
my config

```js
{
	test: /\.(scss)$/,
	loader: ExtractTextPlugin.extract(
		'style?sourceMap',
		'css?sourceMap&modules&importLoaders=1&localIdentName=[local]___[hash:base64:5]',
		'resolve-url?keepQuery',
		'sass?sourceMap'
	)
},
```
my css code
```
.lego{
	font-size: 100px;
	background: url('image/game.png');
}
```

actual output
```
.lego___126xF {
    font-size: 100px;
    background: url(http://localhost:1112/dist/development//image/game.png);
}
```

reproducing: https://github.com/craigcosmo/url-resolve-bug

**Comment by bholloway** [comment]
I'm not seeing anything with a query string or hash. Are you saying that
this example stops working only when you use the keepQuery option?

There's also a lot in webpack config that could be wrong. Can you confirm
this works as a pure CSS file without SASS and resolve Url loaders?

**Comment by craigcosmo** [comment]
Hi, With keepquery on, my file name `game.png` should become like `game.png?dr5t67u9ac343224` right? Or Am i misunderstanding?

**Comment by bholloway** [comment]
Can you update your example to show such a query string. It is not in your
CSS.

**Comment by craigcosmo** [comment]
Can you clarify this, the `keepquery` option is to keep the query string in file name **intact**, It does not generate query string for file name?

**Comment by craigcosmo** [comment]
No I understand, this is not a bug.

**Comment by bholloway** [comment]
You are correct. The option only keeps the query or hash, it does not
generate one.

This loader simply allows webpack to find your asset. Then loaders for the
given asset type will run.

It sounds like you may want cache busting. If so then that can be done
using the hash feature in the file loader.
