### ISSUE TITLE
plugin fails to compile when a mixin with url is added to a global class using css modules

### ISSUE THREAD

**Issue by vzaidman** [bholloway/resolve-url-loader#43]
using webpack 1 and cssmodules.

for the mixin:
`src/common/mixin.scss`:
```
@mixin custom-cursor($cursor-name) {
  cursor: url(common/style/_theme/assets/cursors/#{$cursor-name}.cur), $cursor-name;
}
```

this fails to compile:
`src/some_module/style.scss`
```
@import '../common/mixin';
:global{
  .btn{
    custom-cursor(pointer);
  }
}
```

this works:
`src/some_module/style.scss`
```
@import '../common/mixin';
.btn{
  custom-cursor(pointer);
}
```

**Comment by bholloway** [comment]
From memory I think there is an incompatibility between `rework` and the `:global` directive.

**Comment by bholloway** [comment]
Actually @vzaidman  I believe there are other ways to specify the global. For example `:global(.btn) { ... }`.

Excuse my limited knowledge of css modules but if that is the case, could you please try some alternative syntax and let me know.

**Comment by vzaidman** [comment]
Thank you! This worked!  :zap: :zap: :tada: :tada:
(this is still a workaround and does not solve the bug itself though)

**Comment by bholloway** [comment]
Finally replaced `rework` with `postcss`.

Please refer to #97 as version 3 may help any open issues.

**Comment by bholloway** [comment]
I'm going to close this ageing issue because we have a new version `3.0.0` which (e2e testing confirms) is much better.

Please open a fresh issue for any ongoing problems and link to this one as needed.

I'm not opposed to reopening this issue but certainly lets talk with respect to the new version.
