### ISSUE TITLE
Fix deprecation warning from loader-utils

### ISSUE THREAD

**Issue by cheeaun** [bholloway/resolve-url-loader#47]
Been getting this:

```
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
```

Reference: https://github.com/webpack/loader-utils/issues/56

**Comment by bholloway** [comment]
This looks pretty easy @cheeaun, thanks for bringing to my attention.

**Comment by bholloway** [comment]
I have released a `2.0.1` patch.

Please confirm this fixes the issue and we can close.

**Comment by cheeaun** [comment]
Thanks! I've tried the patch and seems to be working fine so far. I'm mainly getting the deprecation warning from other `loader` dependencies now.

I did some extra checks and there is one more thing; `resolve-url-loader` has a dependency on [`adjust-sourcemap-loader`](https://github.com/bholloway/adjust-sourcemap-loader) which uses the older version of `loader-utils`, so... yeah 😃

**Comment by bholloway** [comment]
Good luck with `adjust-sourcemap-loader`, I hear the package owner is a real pain!

Seriously though, sorry I didn't think of that. Let me see what I can do.

**Comment by cheeaun** [comment]
^ Created an issue there to make it easy for keeping track 😃

**Comment by bholloway** [comment]
Please try `2.0.2` which has the new `adjust-sourcemap-loader`.

The only Webpack 2 project that is close to hand is `sass-loader/example/...` and for some reason it does not give this deprecation warning. So I *hope* this just fixes the problem.

**Comment by cheeaun** [comment]
Seems good so far! Thanks a lot! 👍

**Comment by bholloway** [comment]
Cool. I will close the issue optimistically.

Let me know any problems thought.
