### ISSUE TITLE
Webpack2 configuration problem

### ISSUE THREAD

**Issue by JiDai** [bholloway/resolve-url-loader#54]
Here is my tree : 

```
webpack.config.js
www/
  static/
    sass/
      main.scss
      partials/
        _button.scss
    images/
      button.png
```

Here my loader config
```
{
  test: /main\.scss$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [{
        loader: 'css-loader',
    }, {
        loader: 'postcss-loader'
    }, {
        loader: 'resolve-url-loader'
    }, {
        loader: 'sass-loader',
        options: {
            sourceMap: true,
            includePaths: ['./www/static/sass']
        }
    }],
})
```

And the output tree I want : 

```
www/
  static/
    build/
      css/
        main.css
      images/
        button.png

```

In `buttons.sccs` file I put : 

```
button {
  background: url(../images/button.png)
}
```

But it will be resolve in css file as : 

```
button {
  background: url(images/button.png)
}
```

Why ?
I don't understand how the path in CSS compiled file is deduced
Thanks,

**Comment by Danita** [comment]
I have the same problem, as I understand it's a [problem with the ExtractTextPlugin](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/27).

**Comment by Danita** [comment]
Solved specifying `publicPath: "../"` on the `ExtractTextPlugin.extract()` invocation, as follows:

```js
module: {
  rules: [      
    {
      test: /\.scss$/,
      use: extractSass.extract({
        use: [
          {
            loader: "css-loader",
            options: {
              sourceMap: true
            }
          },            
          {
            loader: "sass-loader",
            options: {
              sourceMap: true
            }
          }
        ],
        publicPath: "../",
      })
    },
  ]
}
```

But then I don't need `resolve-url-loader` anymore because I don't have nested assets.

**Comment by bholloway** [comment]
Thanks @Danita 

So @JiDai I am going to close this issue based on @Danita's solution. We can reopen later if necessary.

**Comment by JiDai** [comment]
Ok thanks, the option `publicPath` in Extract plugin did not work for me. 
But I did specifier the webpack `publicPath` correctly, so once that fixed, it worked.
