### ISSUE TITLE
Unminifies outputStyle: 'compressed' in sass-loader

### ISSUE THREAD

**Issue by StevenTheEVILZ** [bholloway/resolve-url-loader#57]
It appears that this plugin deminifies output from sass-loader.

**Comment by bholloway** [comment]
I see how this seems a reasonable expectation for this loader. However I don't think this property is likely in anything that uses AST under-the-hood.

I would think CSS output format should not be the concern of `sass-loader`. I would hope there are solutions that happen at or after `css-loader`. Maybe take a look at [this suggestion](http://stackoverflow.com/a/37080154) as it may help. Let me know.

Also, from memory there was an issue of some kind with `sass-loader` compressed output and source-maps. But it sounds like everything is working for you so this should not be a problem.

**Comment by Dsantacruz** [comment]
for deminifies output from sass-loader : use: [
            {
                loader: "css-loader",
            },
            {
                loader: "sass-loader",
                query: 
                {
                    outputStyle: 'expanded',
                    sourceMap: true,
                    sourceMapContents: true
                }
            }
        ],
