### ISSUE TITLE
how to add configuration in webpack

### ISSUE THREAD

**Issue by kamil7732** [bholloway/resolve-url-loader#64]
When I try to config the package I get:
`webpack 2 no longer allows custom properties in configuration
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'resolveUrlLoader'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           resolveUrlLoader: ...
         }
       })
     ]

`
Your example looked like:
`module.exports = {
   resolveUrlLoader: {
      ...
   }
}`

so I added it like:
`const path     = require( 'path' );
const HtmlWebpackPlugin = require('html-webpack-plugin');
var webpack = require('webpack');
var CompressionPlugin = require('compression-webpack-plugin');
var StatsPlugin = require('stats-webpack-plugin');

module.exports = {
    context: __dirname,
    stats: "errors-only",
    devtool: 'eval',
    entry: path.join(__dirname, '/src/index.js'),
    output: {
        path: path.join(__dirname, 'uploads', 'js'),
        publicPath: "/js/",
        filename  : 'bundle.js',
        sourceMapFilename: 'bundle.map',
    },
    resolve: {
        extensions: ['.js', '.json'],
        alias: {
            // 'react': 'preact-compat',
            // 'react-dom': 'preact-compat',
            // Not necessary unless you consume a module using `createClass`
            // 'create-react-class': 'preact-compat/lib/create-react-class'
        }
    },
    cache: true,
    watch: true,
    module: {

        loaders   : [
            {
                test  : /\.css$/,
                loader: 'style-loader!resolve-url-loader!css-loader'
            },
            {
                test   : /\.js$/,
                loader : 'babel-loader',
                exclude: /node_modules$/,
                include: path.join(__dirname, '/src')
            },
            {
                test: /\.json$/,
                loader: 'json-loader'
            },
            {
                test   : /\.(jpg|png)$/,
                loader : 'url-loader',
                options: {
                    limit: 25000
                }
            },
            {
                test   : /\.(jpg|png|gif)$/,
                loader : 'file-loader',
                options: {
                    name: '[path][name].[hash].[ext]'
                }
            },
            {
                test: /\.(jpe?g|png|gif|svg)$/i,
                loaders: ['file-loader?context=src/images&name=images/[path][name].[ext]', {
                loader: 'image-webpack-loader',
                query: {
                    mozjpeg: {
                    progressive: true,
                    },
                    gifsicle: {
                    interlaced: false,
                    },
                    optipng: {
                    optimizationLevel: 4,
                    },
                    pngquant: {
                    quality: '75-90',
                    speed: 3,
                    },
                },
                }],
                exclude: /node_modules/,
                include: __dirname,
            },
            {
                test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
                loader: "url-loader?limit=10000&mimetype=application/font-woff"
            },
            {
                test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/,
                loader: "url-loader?limit=10000&mimetype=application/font-woff"
            },
            {
                test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
                loader: "url-loader?limit=10000&mimetype=application/octet-stream"
            },
            {
                test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
                loader: "file-loader"
            },
            {
                test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
                loader: "url-loader?limit=10000&mimetype=image/svg+xml"
            }

        ]
    },
    plugins: [
        new webpack.IgnorePlugin(/^(canvas|mongoose|winston|paypal-rest-sdk|stripe)$/),
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
        }),
        new StatsPlugin('stats.json', {
            chunkModules: true,
            exclude: [/node_modules[\\\/]react/]
        }),
        new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en/)
    ],
    devServer: {
        historyApiFallback: true
    },
    resolveUrlLoader: {

    }
};
`

What am I doing wrong?

**Comment by jschlieber** [comment]
You can find the answer in your error message:

> For loader options: webpack 2 no longer allows custom properties in configuration.
Loaders should be updated to allow passing options via loader options in module.rules.
Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
plugins: [
new webpack.LoaderOptionsPlugin({
// test: /.xxx$/, // may apply this only for some modules
options: {
resolveUrlLoader: ...
}
})
]

**Comment by bholloway** [comment]
Please refer to #97 as version 3 as docs have been updated for webpack 4.
