### ISSUE TITLE
URL:s in mixins are resolved relative to mixin declaration

### ISSUE THREAD

**Issue by nip3o** [bholloway/resolve-url-loader#74]
Let's say we have a file `mixins/mixin.scss` with the following content:

    @mixin my-mixin($image) {
        background-image: url($image);
    }

which is used from the file `my-component/component.scss` like this:

    .component {
        @include my-mixin('./image.png');
    }

In this case I would have assumed that `image.png` was loaded from the `my-component` folder, but it seems to be loaded from whatever folder `mixin.scss` is located in, i.e. `mixins/image.png` in this case. I discovered this only after setting the `attempts` setting to a low value, since the folder is basically irrelevant if unlimited attempts is possible.

Is this somehow by design, or is it a bug? I'll be happy to dig further into this and submit a sample project if you consider it a bug.

**Comment by bholloway** [comment]
I believe it is listed in the limitations in the readme.md

Try to compile a small sass file with the mixin into css with sourcemap.
Check the source map from SASS. I think you will find the source map will
show the mixin file at the point of the url statement.

It is really unfortunate limitation. I hope you can work around it.

**Comment by nip3o** [comment]
Yes, I realize now that the readme says that pretty clearly, I must have missed it somehow. Thanks for the quick response!

**Comment by Dakkers** [comment]
I can't believe that this is just a "known limitation". can you propose a **SOLUTION**? should I just copy and paste my mixin in every single file that needs it?

**Comment by bholloway** [comment]
Please try the `@next` version for V4. This is no longer a limitation. Hopefully V4 can be released soon. 🤞
