### ISSUE TITLE
any way to remove sourcemap?

### ISSUE THREAD

**Issue by waic0083** [bholloway/resolve-url-loader#76]
This plugin requires sourcemap, but I think sourcemap is just use for developing or testing. How can I remove sourcemap on production ?

**Comment by bholloway** [comment]
Source map is just for the loaders before this one. For example the sass
loader.

This loader needs to know where the scss was in order to find the asset
files.

**Comment by bs-thomas** [comment]
@bholloway  Sorry hope you don't mind me kicking in.  For production use, including the sourcemap sounds a bit odd I was just thinking.  Do you have any advice on this?  I don't want other people to start inspecting our sources on a production website.

Thanks in advance!

**Comment by bholloway** [comment]
Please refer to #97. Version 3 has a `test` directory containing a number of sample webpack configurations used for automated testing. I believe this demonstrates production without source-maps.

**Comment by bholloway** [comment]
We have a new version `3.0.0`. There is an example of webpack 4 without sourcemap. As such I am closing this issue.

Please open a fresh issue for any ongoing problems and link to this one as needed.

I'm not opposed to reopening this issue but certainly lets talk with respect to the new version.
