### ISSUE TITLE
background-image: url(...) broken in browser console, might be related to missing sourcemap?

### ISSUE THREAD

**Issue by ishraqiyun77** [bholloway/resolve-url-loader#83]
I posted this issue at [sass-loader](https://github.com/webpack-contrib/sass-loader/issues/544), but think I might have exhausted that avenue. Seeing if I can help here as I am not sure what the issue is related to.
- - - -
Project demonstrating the issue:

https://github.com/ishraqiyun77/url-issue
- - - -
Been trying to get assistance on SO regarding this, but getting no where.

The issue is related to `url()` which the `sass-loader` documentation predicts there might be. Followed the related documentation and am not able to produce the desired result. Essentially, I have a `background-image: url(...)` that isn't loading in the browser despite it point at the correct file and location. The image file is being moved into my `./bundles/img/` directory, the browser is looking at the file in the directory, it just isn't displaying it--it is a broken image icon.

My server does have 404 on these, so it might be related:

![image](https://user-images.githubusercontent.com/33135849/36914692-036550d2-1e03-11e8-9a9c-22c8fab36c4a.png)

My `webpack.config.js` should be producing any relevant sourcemaps:

```
var path = require('path');
var webpack = require('webpack');
var BundleTracker = require('webpack-bundle-tracker');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

const VENDOR_LIBS = [
  'axios', 'history', 'lodash', 'prop-types', 'react', 'react-dom', 'react-dropzone', 'react-redux', 'react-router-dom', 'react-router-redux', 'redux', 'redux-form', 'redux-thunk', 'reactstrap', 'react-responsive'
]

module.exports = {
  context: __dirname,

  entry: {
    app: '../react/index',
    vendor: VENDOR_LIBS
  },

  output: {
      path: path.resolve('./src/assets/bundles/'),
      filename: './js/[name].[chunkhash].js'
  },

  module: {
    rules: [
      { 
        loader: 'babel-loader',
        test: /\.js$/, 
        exclude: /node_modules/, 
        query: {
          presets: ["react", "es2015", "stage-1"]
        }
      },
      {
        test: /\.json$/,
        loader: ['json-loader'] 
      },
      {
        test: /\.png|jpg$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              publicPath: path.resolve('./src/assets/bundles/img/'),
              outputPath: 'img/',
              include: path.join(__dirname, 'assets/img'),
              
            }
          }
        ]
      },
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: {
                sourceMap: true
              }
            },
            {
              loader: 'resolve-url-loader'            
            },
            {
              loader: 'sass-loader?sourceMap',
              options: {
                sourceMap: true
              }
            }
          ]
        })      
      },   
    ],
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest']
    }),
    new BundleTracker({filename: './src/config/webpack-stats.json'}),
    new ExtractTextPlugin({filename: './css/[name].[hash].css', allChunks: true})
  ],
  resolve: {
    extensions: ['*', '.js', '.jsx', '.json', '.gif', '.png'],
  },
}
```

The produced CSS does have sourcemap sections in it.

This is the Sass I am working with:
```
@mixin cust-box($color) {
    background-color: $color;
    padding: 20px;
}

.products {
    .custom-blue-box {
        @include cust-box($blue);
        background-image: url('../img/bg_homebluebox.png');
        margin: 7px;
    }
}
```

This is my directory structure:
```
/app
    /src
        /assets
            /bundles
                /css
               /img
                    a65erg66.png // related to bg_homebluebox.png
                /js
            /img
                bg_homebluebox.png
            /scss
                login.scss
        /config
            webpack.config.js
        /react
            /containers
                /authentication
                    signin.js
            index.js // entry point
```
Here you can see it looking at the image but it isn't loading:

![image](https://user-images.githubusercontent.com/33135849/36914903-b2569a24-1e03-11e8-9c5a-4f1e3b6da588.png)

**Comment by bholloway** [comment]
@ishraqiyun77 I am not sure how the `file-loader` behaves with those options. I do note that your regex is incorrect `/\.png|jpg$/` => `/\.(png|jpg)$/` but that should not make a difference (?)

**Comment by bholloway** [comment]
🤔 In these situations if the assets are placed in the output correctly it _should_ all just work. I will try to take a look as it is an interesting problem but I am pretty snowed under right now.

**Comment by ishraqiyun77** [comment]
Thanks for taking a look! I have a work around for now, but it is definitely an odd problem.

**Comment by bbeesley** [comment]
I may have this same issue, the image is being dumped into the dist directory and referenced correctly, but the version in dist is larger than the original, and corrupted.

**Comment by bholloway** [comment]
Anyone discover any new leads on this?

**Comment by bholloway** [comment]
Okay @ishraqiyun77 having taken another look at your sample project

The output css has an absolute file path, which is never going to work
```css
.products .custom-blue-box {
  background-color: #244289;
  padding: 20px;
  background-image: url(/Users/bholloway/Documents/bholloway/url-issue/src/assets/bundles/img/3b05adf045da970d753c767eb8c63793.png);
  margin: 7px;
}
```

My guess is that it is this line
```
publicPath: path.resolve('./src/assets/bundles/img/'),
```
The `path.resolve()` is going to give you an absolute path. I am previewing your `template.html` in webstorm, so for that in-built webserver I had to set:
```
publicPath: '/url-issue/src/assets/bundles/img',
```
This is different to what you would need but proves that it works.

I think this issue is down to how you deliver your .js, .css, and assets. In my own work I just put all that in the same folder. IMHO you should at least put the assets as some subfolder of css so you can use fully relative `url()` paths in your css. Right now `../assets` from css to image means you will need `publicPath` right to get anything working.

Hope this helps. I'm gonna close for now but feel free to comment further.
