### ISSUE TITLE
Resolved url is absolute

### ISSUE THREAD

**Issue by otoomey** [bholloway/resolve-url-loader#89]
I am loading a css file from a library that in turn loads some font files.
```
/home/otoomey/projects/myproject
 - /dist
 - - index.html
 - - - /fonts
 - - - - font-files.ttf
 - - - - ...
 - /src
 - - /lib
 - - - /css
 - - - - libCssFile.css
 - - - /fonts
 - - - - font-files.ttf
 - - requiresLibCssFile.js
 - - ...
 - webpack.config.js
 - ... 
```
As you can see, the fonts are found correctly and put in my output folder.
My webpack config is very simple:

```javascript
module.exports = {
    mode: 'development',
    entry: {
        app: './src/app.ts'
    },
    devtool: 'inline-source-map',
    devServer: {
        contentBase: './dist'
    },
    output: {
        filename: '[name].bundle.js',
        path: path.resolve(__dirname, 'dist')
    },
    plugins: [
        new HtmlWebpackPlugin({
            title: 'Toch',
            excludeChunks: ['electron']
        }),
        new CleanWebpackPlugin(['dist'])
    ],
    resolve: {
        extensions: [ '.tsx', '.ts', '.js' ]
    },
    module: {
        rules: [{
                test: /\.css$/,
                use: [
                    'style-loader',
                    'css-loader',
                    'resolve-url-loader'
                ]
            },
            {
                test: /\.(png|svg|jpg|gif)$/,
                use: [
                    'file-loader'
                ]
            },
            {
                test: /\.(woff|woff2|eot|ttf|otf)$/,
                use: [
                    'file-loader?name=/fonts/[name].[ext]'
                ]
            },
            {
                test: /\.tsx?$/,
                use: 'ts-loader',
                exclude: '/node_modules/'
            }
        ],
    }
};
```
However, the url in `libCssFile.css` is changed from:
```
src: url("../fonts/materialdesignicons-webfont.eot?v=2.4.85");
```
to:
```
src: url("/fonts/materialdesignicons-webfont.eot?v=2.4.85");
```
Because I am loading the html file directly from the file system into my browser, the `url` is pointing to my own root directory, instead of my project's. Is there a flag I can set to force resolve-url-loader to use a relative path?

**Comment by bholloway** [comment]
@otoomey first let me say that unless you are using something like `sass` then there is nothing for `resolve-url-loader` to "correct" as such. 

Your `url()` statement works completely fine with just CSS. Webpack `css-loader` will look for that file relative to the `.css` file and it will find it. Webpack will then manage that file, which in your case means putting it in your output directory. This is expected and essential. But I'm sure `resolve-url-loader` is doing nothing except slow your build.

The problem you have is that webpack is writing a root-relative url in the final `.css` file. For most people this is usually what they want but of course it requires a web server.

This brings me to a second point. If you are _not_ using some sort of basic web server (including in development) you are going to get a range of similar problems. I would definitely recommend that unless you have some particular reason not to.

Having said all of that I believe you can use the `publicPath` webpack option to prefix _all_ the urls that webpack is writing. From memory, something like `publicPath: '.'` would give you `src: url("./fonts/material...` which is fully relative.

Hope that helps.

**Comment by alxvallejo** [comment]
@bholloway The README is using both a sass-loader and resolve-url-loader. But you're saying if you're using sass then you don't need a resolve-url-loader? That is confusing

**Comment by alxvallejo** [comment]
@bholloway Additionally, from the sass-loader documentation:
>Since Sass/libsass does not provide url rewriting, all linked assets must be relative to the output.

So why are you suggesting that there is nothing this loader to "correct"?

**Comment by bholloway** [comment]
In the example config that @otoomey posted there is no `sass-loader` and no `.scss` files. So in that case there is no need for `resolve-url-loader`.

@alxvallejo If you (a) use `sass-loader` **AND** (b) want feature-centric project structure (relative url in deep sass), then yes there _is_ a use for `resolve-url-loader`.

**Comment by bholloway** [comment]
I'm going to close this issue. Hopefully I have answered suitably and there has been a lack of activity.

Please refer to #97 as version 3 may help any open issues.
