### ISSUE TITLE
"WHAT AM I" is printed to the console for each CSS declaration

### ISSUE THREAD

**Issue by osidenate** [bholloway/resolve-url-loader#91]
This only occurs on the latest version that is published to NPM (2.3.0). It looks like it is fixed in the current codebase, but we need a new version published so that it does not run the log statement.

I get these log statements when I build my project:
![log statments](https://user-images.githubusercontent.com/497417/43217944-dbf70196-8ff7-11e8-8620-08d7836f4dab.png)

I see that this log statement is in `resolve-url-loader/index.js` in the latest version on NPM (2.3.0):
![code](https://user-images.githubusercontent.com/497417/43218051-2aae8610-8ff8-11e8-9923-f47f95a16c38.png)

**Comment by bholloway** [comment]
Trying to reproduce I do this
```sh
npm info resolve-url-loader
```
and I get
```
dist: {
 ...
 tarball: 'https://registry.npmjs.org/resolve-url-loader/-/resolve-url-loader-2.3.0.tgz',
 ...
},
```
then I download and extract that `.tgz` and I get `~/Downloads/package` of the release
```sh
~/Downloads                                                                                                                                                                                        
▶ grep -nr console package                        
package/lib/find-file.js:151:        console.log(text);
```
Manually inspecting `index.js` I don't see the line you quote. Meaning the one causing you the problem.

Can you please perform these steps and see what you get?

**Comment by osidenate** [comment]
I believe the issue is caused by a bug in my organization's private npm proxy, which was returning an incorrect version of resolve-url-loader when I was requesting 2.3.0.

Thanks for the help debugging.
