### ISSUE TITLE
Discussion: Version 3 release

### ISSUE THREAD

**Issue by bholloway** [bholloway/resolve-url-loader#97]
Finally `rework` has been updated to `postcss`!

An alpha is available as [resolve-url-loader@next](https://www.npmjs.com/package/resolve-url-loader/v/3.0.0-alpha.1). This `dist-tag` will be updated as we near release.

Refer to the [readme](https://github.com/bholloway/resolve-url-loader/tree/version-3) for migration instructions.

**Breaking Changes**

- Multiple options changed or deprecated.
- Removed file search "magic" in favour of join option.
- Errors always fail and are no longer swallowed.
- Processing absolute asset paths requires root option to be set.

**Feedback required**

Moving forward on this release is contingent to a few questions..
- [x] is your existing build unchanged when using `engine: rework` ?
- [x] is your build working when using `engine: postcss` (i.e. the new default) ?
- [ ] do you _need_ the file-search "magic" that was removed; is your use-case broken without it ?

And it would be nice to know...
- [x] does this fix any existing [issues](https://github.com/bholloway/resolve-url-loader/issues) ?

**Maturity**

For an alpha this seems (to me) pretty robust.

The only API that is in question is the `join` function. This is advanced feature and is unlikely to be needed by most users. If you intend to use a custom `join` (in place of the file search "magic") then please let me know.

I've not tested any complex (real-world) builds. If you have a use-case you can encode into an example project then I'm definitely interested.

**Comment by rjgotten** [comment]
`engine:rework` seems to work without regression; but continues the trend of having path corruption in source map sources when building on Windows systems.

`engine:postcss` lessens the above path corruption considerably. (Only repeats the rooted disk path once, rather than _n_ times.) However, the _content_ of mapped sources is lost.

**Comment by n-rodriguez** [comment]
> However, the content of mapped sources is lost.

The same here. See https://github.com/bholloway/resolve-url-loader/issues/98#issuecomment-417072239.

**Comment by bholloway** [comment]
So as discussed in #98 there is a fix for output source-map missing `sourcesContent`.

This is [published](https://www.npmjs.com/package/resolve-url-loader/v/3.0.0-alpha.1) as version `3.0.0-alpha.2` with updated dist-tag `next`.

**Comment by n-rodriguez** [comment]
> This is published as version 3.0.0-alpha.2 with updated dist-tag next.

Awesome! It's working well :)

**Comment by rjgotten** [comment]
Working well sofar for the project I'm working on as well.
Haven't heard of further issues than those resolved with alpha.2

**Comment by bholloway** [comment]
@rjgotten from my side I am checking correctness of a billion source-maps from the e2e tests. Following that I am happy to make a `beta` release.

Once at `beta` I am unsure. This is a big rewrite so I am wondering how cautious to be.

Either
* First publish a patch of version 2 to npm that publicises the `@next` version in capitals.
* Just push the button on release and hope for the best.

Happy to take thoughts. If there is any regressions with release then I might be having to make frantic fixes and imposing on those here to retest.

**Comment by bholloway** [comment]
On the subject of outgoing source-maps...

**engine:postcss** 👍 

The mappings look good for the 10 cases in the e2e tests. I reviewed both `development` and `production` output.

The e2e tests are relatively simple cases but it gives some confidence, and really this is `postcss` concern anyhow.

**engine:rework**  - in progress

The mappings look okay in `development`. However `production` looks to be systematically flawed.

I suspected there was a problem for `rework` so I am happy to call this a known issue and move on. I will finish the inspection to see how bad the problem is.

**Comment by bholloway** [comment]
## `3.0.0-beta.1`

If you have tried `3.0.0-beta.1` in dist-tag `resolve-url-loader@next` please vote :thumbsup: or :thumbsdown: for release.

If you vote :thumbsdown: please post detail any problems below.

**Comment by bholloway** [comment]
Only 3 thumbs in a week. But I am inclined to release (today?) anyhow.

**Comment by bholloway** [comment]
🎉 Published as [resolve-url-loader@3.0.0](https://www.npmjs.com/package/resolve-url-loader) 🎉 

Thanks for all your help!

I shall close the issue but please feel free to continue commenting.
