### ISSUE TITLE
Sourcemap paths produced by rework are invalid on Windows

### ISSUE THREAD

**Issue by rjgotten** [bholloway/resolve-url-loader#98]
Rework generates bad source map paths on Windows.

Given the piece of logic that calls out to rework:
https://github.com/bholloway/resolve-url-loader/blob/7105d8a005231bb480cfde082b969d795e36da5e/index.js#L110-L115

If I add some logging of the source map before and after, then here's what I get.

The 'before' from `absSourcemap` (which is stringified into `contentWithMap`):
```
[
  "D:/path-to-project-on-disk/src/styles/main.scss",
  "D:/path-to-project-on-disk/src/styles/_icons.scss",
  "D:/path-to-project-on-disk/src/styles/_typography.scss",
  // ...
]
```

The 'after' from `reworked.map.sources`:
```
[
  "/path-to-project-on-disk/src/styles/main.scss",
  "/path-to-project-on-disk/src/styles/D:/path-to-project-on-disk/src/styles/_icons.scss",
  "/path-to-project-on-disk/src/styles/D:/path-to-project-on-disk/src/styles/_typography.scss",
  // ...
]
```

Not sure what's going on in there, but something in that library you're depending on is definitely broken as hell.

**Comment by bholloway** [comment]
@rjgotten please refer to #97. There has been a lot of effort on a `@next` version that is close to release.

I am hoping that it addresses your issue. Certainly it has automated tests in windows that cover source-map sources.

**Comment by rjgotten** [comment]
@bholloway 
Hmm... From the look of things, this doesn't just fix the corrupt path problem in `resolve-url-loader`, but even prevents the same problem from re-occuring in `postcss-loader` further up the loader stack, as per https://github.com/postcss/postcss-loader/issues/390

**Comment by bholloway** [comment]
@rjgotten I made [this comment](https://github.com/postcss/postcss-loader/issues/340#issuecomment-370458844) some time ago. Is it the same issue in `postcss-loader` or something new?

**Comment by rjgotten** [comment]
@bholloway  
It's that same thing.

**Comment by bholloway** [comment]
:facepalm: As I recall the maintainer wasn't exactly respectful of `resolve-url-loader`. That analysis I did at the time which might interest you (with your :ninja: debug skilz).

Anyhow please let me know how the `@next` goes for you. Particularly if `engine:rework` works without regression it would be nice to hear that in #97.

Also feel free to keep commenting here too.

**Comment by bholloway** [comment]
Cool. Thanks for the comment in #97. I will shift back here to discuss in detail and we can return there if there is some conclusions...

🤔 Just thinking of bholloway/adjust-sourcemap-loader#3. Is it that there are these additional paths present? As I said there I don't use `sourcesContent` so I would need to check that code path.

Sounds like we will need a simple example project I can debug.

**Comment by rjgotten** [comment]
I've hooked back up my little 'source map spy' loader and checked.
`sourcesContent` is present when the `rework` engine is used, but _not_ when the `postcss` engine is used.

**Comment by bholloway** [comment]
Ah my fault, sorry. Look [here](https://github.com/bholloway/resolve-url-loader/blob/version-3/packages/resolve-url-loader/lib/engine/postcss.js#L33).

Okay I will change that and run tests overnight (late here). Presumably I can do do an `alpha.2` tomorrow and update dist-tag `next`.

**Comment by rjgotten** [comment]
@bholloway 
Just found that. Looks like replacing it with `"sourcesContent" in absSourceMap` is what you want here.
I.e. if the incoming source map was already based on inlined sources; keep them. If not; don't bother making them.

**Comment by bholloway** [comment]
@rjgotten maybe I should just delete the highlighted line. Is that how you interpret [options](https://github.com/postcss/postcss/blob/master/docs/source-maps.md#options) docs?

**Comment by bholloway** [comment]
@rjgotten can you pls monkey patch that line as `sourcesContent: true` and just make sure it is working for you in your local copy. I have the change in progress but immediate feedback is always good.

**Comment by rjgotten** [comment]
@bholloway 
It works with `true` locally. :)

**Comment by n-rodriguez** [comment]
@bholloway : the same happens on Linux :

```sh
Impossible de récupérer la source d’origine : TypeError: NetworkError when attempting to fetch resource.
URL de la source : webpack:///node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss
```
Changing `sourcesContent` to `true` in local `resolve-url-loader/lib/engine/postcss.js` file solves the issue.

**Comment by bholloway** [comment]
Ah thanks @n-rodriguez. So existing tests passed, I am moving forward with this change to the alpha. Will ping you when its released.

**Comment by n-rodriguez** [comment]
> So existing tests passed, I am moving forward with this change to the alpha. Will ping you when its released.

Great :)

**Comment by bholloway** [comment]
Ping @rjgotten @n-rodriguez see [comment](https://github.com/bholloway/resolve-url-loader/issues/97#issuecomment-417155090).

Please let me know here if you have further feedback.

**Comment by bholloway** [comment]
Ping @rjgotten @n-rodriguez released `3.0.0`. Please let me know if we can close this issue.

**Comment by n-rodriguez** [comment]
@bholloway : it's already in production :)

**Comment by bholloway** [comment]
Sounds good. Pleasure working with you on this. That said I'll add the footnote I've been using to close out the other existing issues 😉 ...

Please open a fresh issue for any ongoing problems and link to this one as needed.

I'm not opposed to reopening this issue but certainly lets talk with respect to the new version.
